mounts:
  - source: layouts
    target: layouts
  - source: layouts/_work_types
    target: layouts/work_types
  - source: content
    target: content
  - source: remote/wp/pages
    target: content/pages
    lang: e
  - source: remote/wp/publications
    target: content/publications
    lang: en
  - source: remote/wp/authors
    target: content/authors
    lang: en
  - source: remote/wp/work_types
    target: content/work_types
    lang: en
  - source: remote/sanity/post
    target: content/articles
    lange: en
  - source: remote/sanity/movie
    target: content/movies
    lang: en
  - source: remote/sanity/person
    target: content/persons
    lang: en
imports:
  - path: github.com/theNewDynamic/hugo-module-tnd-seo
  - path: github.com/theNewDynamic/hugo-module-tnd-styles
  - path: github.com/theNewDynamic/unit-tests
    ignoreConfig: true
    mounts:
    - source: content/unit-tests
      target: content/articles
      lang: en